# Generated by Django 6.0.7 on 2026-07-15 16:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jina la Duka')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Duka Slug (Njia ya URL)')),
                ('store_type', models.CharField(choices=[('sabuni', 'Wholesale Soaps (Sabuni za Jumla)'), ('mafuta', 'Edible Oils (Mafuta ya Kupikia)'), ('mixer', 'General Household / Mixer (Duka Mchanganyiko)'), ('vyombo', 'Kitchenware / Household Items (Vyombo na Vyombo vya Nyumbani)')], default='mixer', max_length=20, verbose_name='Aina ya Duka')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Nembo ya Duka')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Bango la Duka (Banner)')),
                ('theme_color', models.CharField(default='#2563eb', max_length=7, verbose_name='Rangi ya Mandhari (Theme Hex)')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='Namba ya WhatsApp ya Maagizo')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo Mafupi ya Duka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Duka',
                'verbose_name_plural': 'Maduka',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Jina la Kategoria')),
                ('duka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.duka')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategoria',
                'unique_together': {('duka', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('owner', 'Store Owner (Mmiliki)'), ('cashier', 'Cashier (Muuzaji)')], default='cashier', max_length=10, verbose_name='Jukumu')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('duka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.duka', verbose_name='Duka analofanyia kazi')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Jina la Mteja')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Namba ya Simu')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending (Kusubiri)'), ('completed', 'Completed (Tayari)'), ('cancelled', 'Cancelled (Kufutwa)')], default='pending', max_length=15)),
                ('duka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.duka')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jina la Bidhaa')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo ya Bidhaa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Picha ya Bidhaa')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Bei ya Kununulia (Cost Price)')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Bei ya Kuuzia (Selling Price)')),
                ('stock_level', models.IntegerField(default=0, verbose_name='Kiasi Kilichopo Stoo')),
                ('min_stock_alert', models.IntegerField(default=5, verbose_name='Kiwango cha Kutoa Taarifa (Reorder Alert)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category')),
                ('duka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.duka')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bei Wakati wa Kuagiza')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash (Fedha Taslimu)'), ('m-pesa', 'M-Pesa'), ('tigopesa', 'Tigo Pesa'), ('airtelmoney', 'Airtel Money'), ('halo-pesa', 'Halo Pesa'), ('card', 'Bank Card / Visa')], default='cash', max_length=20)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('duka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.duka')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bei Wakati wa Mauzo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.sale')),
            ],
        ),
    ]
