# Generated by Django 6.0.7 on 2026-07-16 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash (Fedha Taslimu)'), ('m-pesa', 'M-Pesa'), ('tigopesa', 'Tigo Pesa'), ('airtelmoney', 'Airtel Money'), ('halo-pesa', 'Halo Pesa'), ('card', 'Bank Card / Visa'), ('debt', 'Deni / Mkopo')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jina la Mteja')),
                ('phone', models.CharField(max_length=20, verbose_name='Namba ya Simu')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Barua Pepe')),
                ('address', models.TextField(blank=True, verbose_name='Anwani / Maelezo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.duka')),
            ],
            options={
                'verbose_name': 'Mteja',
                'verbose_name_plural': 'Wateja',
                'unique_together': {('duka', 'phone')},
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.customer', verbose_name='Mteja (kwa Mauzo ya Deni)'),
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kiasi cha Deni')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kiwango Kilichobaki')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Tarehe ya Mwisho ya Kulipa')),
                ('status', models.CharField(choices=[('unpaid', 'Haijalipwa (Unpaid)'), ('partially_paid', 'Imelipwa Kiasi (Partially Paid)'), ('paid', 'Imelipwa Yote (Paid)')], default='unpaid', max_length=20, verbose_name='Hadhi ya Deni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Maelezo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='core.customer')),
                ('duka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='core.duka')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='core.sale', verbose_name='Mauzo Husika')),
            ],
            options={
                'verbose_name': 'Deni',
                'verbose_name_plural': 'Madeni',
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kiasi Kilicholipwa')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarehe ya Malipo')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash (Fedha Taslimu)'), ('m-pesa', 'M-Pesa'), ('tigopesa', 'Tigo Pesa'), ('airtelmoney', 'Airtel Money'), ('halo-pesa', 'Halo Pesa'), ('card', 'Bank Card / Visa')], default='cash', max_length=20, verbose_name='Njia ya Malipo')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.debt')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mpokeaji (Cashier)')),
            ],
            options={
                'verbose_name': 'Malipo ya Deni',
                'verbose_name_plural': 'Malipo ya Madeni',
            },
        ),
    ]
